[changelog]
header = """
# Changelog

All notable changes are documented here. The format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
body = """
## What's New

{% for commit in commits %}{% if commit.author.name is not containing("[bot]") %}- {{ commit.message | split(pat="\n") | first | trim }} (by @{{ commit.author.name }}){% if commit.github.pr_number %} (#{{ commit.github.pr_number }}){% endif %} [{{ commit.id | truncate(length=7, end="") }}]
{% endif %}{% endfor %}
{% if previous.version %}**Full changelog:** [{{ previous.version }}..{{ version }}](https://github.com/areebahmeddd/airhop/compare/{{ previous.version }}..{{ version }})
{% endif %}
"""
footer = ""
trim = false

[git]
conventional_commits = false
filter_unconventional = false
filter_commits = true
commit_parsers = [
  { message = "^chore\\(release\\):", skip = true },
  { message = "^[a-z]+(\\(.+?\\))?!?:", skip = false },
  { message = ".*", skip = true },
]
tag_pattern = "v[0-9].*"
topo_order = false
sort_commits = "newest"
