// Generated by cbindgen from native/arti/src/ffi_c.rs. Do not edit.
// Regenerate with native/arti/build-apple.sh.

#ifndef AIRHOP_ARTI_H
#define AIRHOP_ARTI_H

#include <stdint.h>
#include <stdbool.h>

/**
 * Return codes shared by both FFI surfaces.
 *
 * Plain integers because that is all a C ABI and a JNI `jint` can carry. Both
 * the Swift and the Kotlin module mirror these by name, so no call site ever
 * compares against a bare number.
 */
#define AIRHOP_TOR_OK 0

/**
 * A client is already running. Stop it first.
 */
#define AIRHOP_TOR_ERR_ALREADY_RUNNING -1

/**
 * The data directory was not valid UTF-8, or could not be created.
 */
#define AIRHOP_TOR_ERR_DATA_DIR -2

/**
 * The async runtime could not be created.
 */
#define AIRHOP_TOR_ERR_RUNTIME -3

/**
 * The Tor client could not be constructed. Usually a locked or unwritable
 * state directory.
 */
#define AIRHOP_TOR_ERR_CLIENT -4

/**
 * The SOCKS port could not be bound. Usually something else holds it.
 */
#define AIRHOP_TOR_ERR_BIND -5

/**
 * Nothing is running, so there was nothing to do.
 */
#define AIRHOP_TOR_ERR_NOT_RUNNING -6

/**
 * A bridge line could not be parsed.
 */
#define AIRHOP_TOR_ERR_BRIDGE_LINE -7

/**
 * A bridge line names a transport Airhop does not ship, or one whose local
 * proxy is not running, or carries more settings than a SOCKS5 handshake
 * can pass to it.
 */
#define AIRHOP_TOR_ERR_BRIDGE_TRANSPORT -8

/**
 * A panic was caught at the FFI boundary. The call did nothing; the reason is
 * in the status summary.
 */
#define AIRHOP_TOR_ERR_PANIC -9

/**
 * Bit layout of the packed status word both FFI surfaces return.
 *
 * ```text
 *   bit  0      running
 *   bit  1      ready
 *   bit  2      blocked
 *   bit  3      bridged
 *   bits 8..15  progress, 0 to 100
 * ```
 *
 * One integer, not a struct, for two reasons. It is the only shape both
 * a C ABI and a JNI `jint` express natively, so Swift needs no assumption about
 * how a Rust struct is laid out and Kotlin needs no class lookup. And a single
 * return value is a single consistent snapshot by construction, where a struct
 * filled field by field is only as atomic as the lock around it.
 *
 * `AirhopTorManager.swift` and `ArtiNative.kt` hold the matching decoders, so
 * no call site on either platform does bit arithmetic.
 */
#define AIRHOP_TOR_STATUS_RUNNING (1 << 0)

#define AIRHOP_TOR_STATUS_READY (1 << 1)

#define AIRHOP_TOR_STATUS_BLOCKED (1 << 2)

#define AIRHOP_TOR_STATUS_BRIDGED (1 << 3)

#define AIRHOP_TOR_STATUS_PROGRESS_SHIFT 8

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Start Tor and bind its SOCKS5 listener on `127.0.0.1:socks_port`,
 * reaching the network through `bridge_lines` when any are given.
 *
 * `bridge_lines` is a newline-separated list in standard Tor format; empty or
 * null is a direct connection to a public relay. `obfs4_port` and
 * `snowflake_port` are where the app already has each transport listening on
 * loopback, or `0` when it does not, and a line naming a transport whose port
 * is `0` is refused rather than started without it.
 *
 * Returns `0` once the listener is accepting, which is before the first
 * circuit exists. Any other value is one of the `AIRHOP_TOR_ERR_*` codes. A bad
 * line stops the start: nothing binds and nothing bootstraps.
 *
 * # Safety
 *
 * `data_dir` must be a non-null, NUL-terminated C string, and `bridge_lines`
 * either null or the same. Both must stay valid for the duration of the call.
 */
int airhop_tor_start(const char *data_dir, uint16_t socks_port, const char *bridge_lines, uint16_t obfs4_port, uint16_t snowflake_port);

/**
 * Stop Tor, drop its client and release the port. Returns `0`, or
 * `AIRHOP_TOR_ERR_NOT_RUNNING` when there was nothing to stop.
 */
int airhop_tor_stop(void);

/**
 * Put Tor to sleep or wake it, for the app leaving and re-entering the
 * foreground. Returns `0`, or `AIRHOP_TOR_ERR_NOT_RUNNING`.
 */
int airhop_tor_set_dormant(bool dormant);

/**
 * The current status, packed into one word.
 *
 * ```text
 *   bit  0      running
 *   bit  1      ready
 *   bit  2      blocked
 *   bit  3      bridged
 *   bits 8..15  progress, 0 to 100
 * ```
 *
 * Never fails, and is safe to call at any time including before a start and
 * after a stop, where it reports a stopped client rather than an error. That is
 * why it returns the status directly rather than a status code with an out
 * parameter: there is no failure for a caller to handle.
 */
int airhop_tor_status(void);

/**
 * Copy Arti's current stage description into `buf` as a NUL-terminated string.
 *
 * Returns the number of bytes written excluding the terminator, or a negative
 * error. Truncates on a short buffer instead of failing, and truncates on a
 * character boundary so the result is always valid UTF-8: this is display text,
 * and a clipped sentence beats no sentence.
 *
 * # Safety
 *
 * `buf` must be non-null and point at `len` writable bytes.
 */
int airhop_tor_summary(char *buf, int len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AIRHOP_ARTI_H */
