// Bakes the globe used by the last panel.
//
//   node press/tools/generate-world.mjs
//
// Projects the land outline and every Nostr relay in landing/src/data/relays.ts
// onto an orthographic globe and writes press/lib/world.mjs as flat path data.
// Doing it here keeps d3-geo and world-atlas out of the renderer.
//
// Re-run after editing the relay list.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const LANDING = join(ROOT, "landing");

const mod = (rel) => import(`file:///${join(LANDING, rel).replace(/\\/g, "/")}`);
const { geoOrthographic, geoPath, geoDistance, geoGraticule10 } = await mod(
  "node_modules/d3-geo/src/index.js",
);
const { feature } = await mod("node_modules/topojson-client/src/index.js");

const SIZE = 640;
const PADDING = 6;

// Centred on the mid-Atlantic. Both Americas, Europe and Africa are on the
// visible face, which is where nearly every relay in the list actually is.
const CENTRE = [-32, 22];
const ROTATE = [-CENTRE[0], -CENTRE[1]];

function readRelaySites() {
  const src = readFileSync(join(LANDING, "src/data/relays.ts"), "utf8");
  const sites = [];
  const re = /\{\s*lat:\s*(-?[\d.]+),\s*lng:\s*(-?[\d.]+),\s*relays:\s*(\d+)/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    sites.push({ lat: Number(m[1]), lng: Number(m[2]), relays: Number(m[3]) });
  }
  const countMatch = /RELAY_COUNT\s*=\s*(\d+)/.exec(src);
  return { sites, total: countMatch === null ? sites.length : Number(countMatch[1]) };
}

function dotRadius(relays) {
  return Math.min(6.5, 1.8 + Math.sqrt(relays) * 0.5);
}

// Minimum spanning tree over great-circle distance, so the arcs join each site
// to its nearest neighbour instead of drawing a hairball.
function spanningEdges(sites) {
  const count = sites.length;
  if (count < 2) return [];
  const reached = new Array(count).fill(false);
  const cost = new Array(count).fill(Infinity);
  const from = new Array(count).fill(0);
  const edges = [];
  cost[0] = 0;

  for (let step = 0; step < count; step++) {
    let next = -1;
    for (let i = 0; i < count; i++) {
      if (!reached[i] && (next < 0 || cost[i] < cost[next])) next = i;
    }
    reached[next] = true;
    if (step > 0) edges.push([from[next], next]);

    const origin = [sites[next].lng, sites[next].lat];
    for (let i = 0; i < count; i++) {
      if (reached[i]) continue;
      const d = geoDistance(origin, [sites[i].lng, sites[i].lat]);
      if (d < cost[i]) {
        cost[i] = d;
        from[i] = next;
      }
    }
  }
  return edges;
}

const round = (s) => s.replace(/(\d+\.\d)\d+/g, "$1");

const topology = JSON.parse(
  readFileSync(join(LANDING, "node_modules/world-atlas/land-110m.json"), "utf8"),
);
const land = feature(topology, topology.objects.land);

const projection = geoOrthographic()
  .rotate(ROTATE)
  .fitExtent(
    [
      [PADDING, PADDING],
      [SIZE - PADDING, SIZE - PADDING],
    ],
    { type: "Sphere" },
  );
const path = geoPath(projection);

const landPath = round(path(land));
const graticulePath = round(path(geoGraticule10()));

const { sites, total } = readRelaySites();

// The projection returns coordinates for points round the back too, mirrored
// onto the front, so visibility is decided by angle from the centre. The far
// side is kept, to be drawn as a ghost.
const front = [];
const back = [];
for (const site of sites) {
  const p = projection([site.lng, site.lat]);
  if (p === null) continue;
  const visible = geoDistance([site.lng, site.lat], CENTRE) < Math.PI / 2;
  const dot = [Number(p[0].toFixed(1)), Number(p[1].toFixed(1)), Number(dotRadius(site.relays).toFixed(2))];
  if (visible) front.push(dot);
  else back.push(dot);
}

// geoPath resamples a two-point LineString along the geodesic and clips it at
// the horizon, so an arc that runs round the back simply stops at the edge.
const arcs = [];
for (const [a, b] of spanningEdges(sites)) {
  const d = path({
    type: "LineString",
    coordinates: [
      [sites[a].lng, sites[a].lat],
      [sites[b].lng, sites[b].lat],
    ],
  });
  if (d !== null && d.length > 0) arcs.push(round(d));
}

const out = `// Generated by press/tools/generate-world.mjs. Do not edit by hand.
//
// Orthographic globe centred on ${CENTRE[0]}, ${CENTRE[1]}: land outline,
// 10-degree graticule and every relay location, at a ${SIZE}x${SIZE} viewBox.

export const GLOBE_SIZE = ${SIZE};
export const LAND_PATH = ${JSON.stringify(landPath)};
export const GRATICULE_PATH = ${JSON.stringify(graticulePath)};
export const RELAY_DOTS_FRONT = ${JSON.stringify(front)};
export const RELAY_DOTS_BACK = ${JSON.stringify(back)};
export const RELAY_ARCS = ${JSON.stringify(arcs)};
`;

writeFileSync(join(ROOT, "press/lib/world.mjs"), out);
console.log(
  `world.mjs: ${front.length} front / ${back.length} back sites, ${total} relays, ${arcs.length} arcs, ${(out.length / 1024).toFixed(0)}KB`,
);
