// Bakes the Feather icon set into lib/feather.mjs.
//
//   node press/tools/generate-icons.mjs
//
// The app draws with @react-native-vector-icons/feather. A headless browser
// cannot load that, so the same glyphs are taken from the feather-icons
// package, which film/ installs, and written out as plain SVG markup. Doing it
// here keeps the package out of the renderers, and keeps the glyphs exact
// instead of transcribed by hand.
//
// Re-run after bumping feather-icons in film/package.json.

import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PRESS = join(dirname(fileURLToPath(import.meta.url)), "..");

// Loaded by path, the way generate-world.mjs reaches into landing/: press/
// has no package.json of its own.
const require = createRequire(import.meta.url);
const packageDir = join(PRESS, "film", "node_modules", "feather-icons");
const feather = require(packageDir);
const { version } = require(join(packageDir, "package.json"));

const names = Object.keys(feather.icons).sort();
const entries = names.map(
  (name) => `  ${JSON.stringify(name)}: ${JSON.stringify(feather.icons[name].contents)},`,
);

const out = `// Generated by press/tools/generate-icons.mjs. Do not edit by hand.
//
// Feather ${version}: the inner markup of every glyph, at the 24x24 viewBox.

export const FEATHER = {
${entries.join("\n")}
};
`;

writeFileSync(join(PRESS, "lib", "feather.mjs"), out);
console.log(`feather.mjs: ${names.length} icons, ${(out.length / 1024).toFixed(0)}KB`);
