#!/usr/bin/env node
// Refreshes the built-in bridge lines in src/data/bridges.ts.
//
//   node scripts/sync-bridges.js --input <moat.json>
//   node scripts/sync-bridges.js --input <moat.json> --check
//
// The input is the response from the Tor Project's Moat "builtin" endpoint,
// which is where Tor Browser gets the same list. The workflow fetches it; this
// only validates and writes, so it can be run against a saved payload.
//
// obfs4 lines are public and are the first thing a censor enumerates, so a list
// frozen at release time goes stale between store updates and fails exactly
// where a user needs it, while looking like the safe choice.

const fs = require("fs");
const path = require("path");

const OUTPUT = path.join("src", "data", "bridges.ts");

// Transports Airhop ships. Moat also returns meek and meek-azure, which Airhop
// does not run, so they are dropped rather than written to a file that implies
// they work.
const WANTED = ["obfs4", "snowflake"];

// Sanity bounds on the upstream answer. A response that parses but carries one
// bridge, or a hundred, is more likely a changed API or a bad day upstream than
// a real list, and adopting it silently is how a broken release ships.
const LIMITS = {
  obfs4: { min: 3, max: 40 },
  snowflake: { min: 1, max: 8 },
};

// Arti packs a transport's settings into the SOCKS5 username and password when
// it dials the local proxy, 255 bytes each. Mirrors MAX_PT_SETTINGS_BYTES in
// native/arti/src/bridges.rs; a longer line is refused there at start.
const MAX_PT_SETTINGS_BYTES = 255 * 2;

function fail(message) {
  console.error(`error: ${message}`);
  process.exit(1);
}

function arg(name) {
  const i = process.argv.indexOf(name);
  return i === -1 ? undefined : process.argv[i + 1];
}

// The settings a line carries, as tor-chanmgr would encode them: `k=v` pairs
// joined by `;`, with `\` and `;` escaped in both halves and `=` only in keys.
function settingsBytes(line) {
  const escaped = (s, chars) =>
    s.length + [...s].filter((c) => chars.includes(c)).length;
  const words = line.split(/\s+/).filter((w) => w.includes("="));
  const total = words.reduce((sum, word) => {
    const at = word.indexOf("=");
    return (
      sum +
      escaped(word.slice(0, at), "\\;=") +
      1 +
      escaped(word.slice(at + 1), "\\;") +
      1
    );
  }, 0);
  return Math.max(0, total - 1);
}

// Throws rather than exits, so a test can see which line was refused.
function validate(transport, lines) {
  const refuse = (message) => {
    throw new Error(message);
  };

  const limit = LIMITS[transport];
  if (lines.length < limit.min || lines.length > limit.max) {
    refuse(
      `${transport}: upstream returned ${lines.length} bridges, expected ${limit.min} to ${limit.max}`,
    );
  }

  for (const line of lines) {
    // Printable ASCII words separated by single spaces, the pt-spec grammar.
    // The file joins its entries with newlines, so one carrying a newline
    // would become two bridge lines of which only the first was checked.
    if (
      typeof line !== "string" ||
      !/^[\x21-\x7e]+(?: [\x21-\x7e]+)*$/.test(line)
    ) {
      refuse(
        `${transport}: a line is not printable ASCII on one line: ${JSON.stringify(line)}`,
      );
    }
    if (!line.startsWith(`${transport} `)) {
      refuse(`${transport}: a line does not name its own transport: ${line}`);
    }
    // Address and identity, then the settings. Arti refuses a line missing
    // either, and finding that out at start is worse than finding it here.
    const [, address, fingerprint] = line.split(" ");
    if (!/^[\d.]+:\d+$|^\[[\da-f:]+\]:\d+$/i.test(address ?? "")) {
      refuse(`${transport}: no address:port in: ${line}`);
    }
    if (!/^[0-9A-F]{40}$/i.test(fingerprint ?? "")) {
      refuse(`${transport}: no relay fingerprint in: ${line}`);
    }
    const bytes = settingsBytes(line);
    if (bytes > MAX_PT_SETTINGS_BYTES) {
      refuse(
        `${transport}: settings are ${bytes} bytes, over the ${MAX_PT_SETTINGS_BYTES} a SOCKS5 handshake can carry: ${line}`,
      );
    }
  }

  if (transport === "snowflake") {
    for (const line of lines) {
      // Without these the connection still works but is easier to pick out,
      // which defeats the point of using it.
      for (const setting of ["url=", "fronts=", "ice=", "utls-imitate="]) {
        if (!line.includes(setting)) {
          refuse(`snowflake: line is missing ${setting}: ${line}`);
        }
      }
    }
  }
}

function render(bridges) {
  const block = (lines) =>
    lines.map((line) => `  ${JSON.stringify(line)},`).join("\n");

  return `// Built-in bridge lines. Generated by scripts/sync-bridges.js from
// Moat, the same source Tor Browser uses. Do not edit by hand.

// Fast, but these lines are public and a determined censor blocks them.
export const OBFS4_BRIDGE_LINES = [
${block(bridges.obfs4)}
].join("\\n");

// Slower, but reaches a volunteer proxy through a broker, so there is no list
// to enumerate and it still works where obfs4 does not.
export const SNOWFLAKE_BRIDGE_LINES = [
${block(bridges.snowflake)}
].join("\\n");
`;
}

function main() {
  const input = arg("--input");
  if (!input) fail("pass --input <moat.json>");

  let payload;
  try {
    payload = JSON.parse(fs.readFileSync(input, "utf8"));
  } catch (error) {
    fail(`could not read ${input}: ${error.message}`);
  }

  const bridges = {};
  for (const transport of WANTED) {
    const lines = payload[transport];
    if (!Array.isArray(lines)) {
      fail(`upstream response has no ${transport} list`);
    }
    // Sorted so an unchanged set produces an unchanged file whatever order
    // upstream answered in, and a diff only appears when the set really moved.
    // A non-string is left for validate to refuse by name.
    bridges[transport] = lines
      .map((l) => (typeof l === "string" ? l.trim() : l))
      .sort();
    try {
      validate(transport, bridges[transport]);
    } catch (error) {
      fail(error.message);
    }
  }

  const rendered = render(bridges);

  if (process.argv.includes("--check")) {
    const current = fs.existsSync(OUTPUT)
      ? fs.readFileSync(OUTPUT, "utf8")
      : "";
    if (current !== rendered) {
      fail(
        `${OUTPUT} is out of date; run node scripts/sync-bridges.js --input ${input}`,
      );
    }
    console.log(`${OUTPUT} matches upstream.`);
    return;
  }

  fs.writeFileSync(OUTPUT, rendered);
  console.log(
    `Wrote ${OUTPUT}: ${bridges.obfs4.length} obfs4, ${bridges.snowflake.length} snowflake.`,
  );
}

if (require.main === module) main();
else module.exports = { validate };
